# Generated by Django 6.0.2 on 2026-04-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='cryptographic_signature',
            field=models.TextField(blank=True, help_text='RSA PKCS#1v1.5 signature of job data'),
        ),
    ]
