# Generated by Django 6.0.2 on 2026-04-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_securityauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityauditlog',
            name='current_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
