# Generated by Django 6.0.2 on 2026-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_securityauditlog_current_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True),
        ),
    ]
