# Generated by Django 6.0.2 on 2026-04-13 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_private_key_encrypted_user_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('summary', models.TextField(blank=True, help_text='Short professional bio or objective.')),
                ('education', models.TextField(blank=True, help_text='List your degrees and universities.')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
