# Generated by Django 6.0.2 on 2026-04-13 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_candidateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='opt_out_view_tracking',
            field=models.BooleanField(default=False, help_text='Do not track who viewed your profile, and do not let others see you viewed theirs.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='privacy_education',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='privacy_skills',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='privacy_summary',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15),
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('viewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
