# Generated by Django 6.0.2 on 2026-04-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_candidateprofile_opt_out_view_tracking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='education',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('start_month', models.CharField(blank=True, max_length=20)),
                ('start_year', models.CharField(blank=True, max_length=4)),
                ('end_month', models.CharField(blank=True, max_length=20)),
                ('end_year', models.CharField(blank=True, max_length=4)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.candidateprofile')),
            ],
            options={
                'ordering': ['-end_year', '-start_year'],
            },
        ),
    ]
