# Generated by Django 6.0.2 on 2026-04-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_candidateprofile_education_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='privacy_education',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='privacy_skills',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='privacy_summary',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', help_text='Who can see your profile details?', max_length=15),
        ),
    ]
