# Generated by Django 6.0.2 on 2026-04-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_candidateprofile_privacy_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Longer profile bio.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='Professional headline.', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Current location.', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='privacy_bio',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='privacy_education',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='privacy_experience',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='privacy_headline',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='privacy_location',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='privacy_photo',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='privacy_skills',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='privacy_summary',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('start_month', models.CharField(blank=True, max_length=20)),
                ('start_year', models.CharField(blank=True, max_length=4)),
                ('end_month', models.CharField(blank=True, max_length=20)),
                ('end_year', models.CharField(blank=True, max_length=4)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.candidateprofile')),
            ],
            options={
                'ordering': ['-end_year', '-start_year'],
            },
        ),
    ]
