# Generated by Django 6.0.2 on 2026-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='group_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
