# Generated by Django 6.0.2 on 2026-04-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_resume_owner_name_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parsed_keywords',
            field=models.TextField(blank=True, help_text='AI Extracted keywords from the raw PDF'),
        ),
    ]
